### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by asimonv** [IIC2513-2017-2/syllabus#10]
Podemos usar ajax?

**Comment by raulmt** [comment]
@asimonv vamos a usar Ajax en el curso, pero está programado a la altura de la entrega 5. En todo caso, si te quieres adelantar bienvenido. Sólo ten en cuenta que veremos este tema potencialmente con una aproximación diferente de la que puedas verlo tú antes y, por lo tanto, quizá implique que debas agregar o cambiar algunas cosas en tu proyecto más adelante.
