### ISSUE TITLE
Recordatorio entrega 2

### ISSUE THREAD

**Issue by negebauer** [IIC2513-2017-2/syllabus#11]
@IIC2513-2017-2/alumnos 

Un pequeño recordatorio de algunos puntos importantes para la [entrega 2](https://github.com/IIC2513-2017-2/syllabus/blob/master/Proyecto/enunciados/Entrega2.md)

1. La entrega se revisa en base al estado de la branch `master`. No se olviden de mergear su trabajo si lo han hecho en otras branches.
1. La aplicación debe estar montada en [Heroku](https://www.heroku.com/)
1. Coloquen la url de su aplicación Heroku en su README.md

Que tengan una buena entrega y disfruten el fin de semana!

**Comment by negebauer** [comment]
@IIC2513-2017-2/alumnos 
Varios han tenido problemas haciendo el deploy a heroku así que aquí les tengo una pequeña guía para ello. También van a tener hasta **mañana a la misma hora** para terminar
A todos ustedes se les debería haber abierto un PR parecido al que tiene IIC2513-2017-2/wican#4
Ese PR tiene cambios necesarios para que su aplicación pueda correr en heroku, en particular

1. Configurar el engine (versiones de node y yarn) que tiene que usar Heroku para que no tenga problemas de syntax
2. Configurar la versión production de la base de datos usando `DATABASE_URL`, que es donde Heroku expone los datos de su db

Para hacerles más fácil el deploy les tengo una pequeña guía
Si la siguen al pie de la letra deberían tener su app funcionando en Heroku sin problemas!

***

Primero creamos la aplicación en Heroku y le damos un nombre

<img width="1439" alt="crear 1" src="https://user-images.githubusercontent.com/11860880/30507775-858a51a2-9a5f-11e7-9ff4-a3938dc81d3b.png">

Vamos a la pantalla de Settings

<img width="585" alt="settings" src="https://user-images.githubusercontent.com/11860880/30507781-a207e164-9a5f-11e7-96b0-589b395e5453.png">

Bajamos hasta la sección buildpacks y seleccionamos agregar uno nuevo

<img width="1221" alt="buildpacks" src="https://user-images.githubusercontent.com/11860880/30507786-c62394c6-9a5f-11e7-80c9-366b3268d319.png">

Seleccionamos el buildpack de node

<img width="625" alt="buildpack 2" src="https://user-images.githubusercontent.com/11860880/30507792-d15c0b70-9a5f-11e7-8a9f-17a9a35fead1.png">

Vamos a la pantalla de Resources

<img width="585" alt="resources" src="https://user-images.githubusercontent.com/11860880/30507803-ee5d56f2-9a5f-11e7-8780-18caea3e183d.png">

En la sección de add ons buscamos Postgres y lo agregamos

<img width="1220" alt="postgres" src="https://user-images.githubusercontent.com/11860880/30507807-064dcfa8-9a60-11e7-92b8-763ef3da8a8c.png">

Seleccionan la versión gratuita

<img width="482" alt="postgres 2" src="https://user-images.githubusercontent.com/11860880/30507813-1ade1450-9a60-11e7-8311-f3f29250b1d9.png">

Luego vuelven a la pestaña de Settings, bajan a Config Variables, hacen click en Reveal Config Vars y debería aparecer una DATABASE_URL siguiendo un formato parecido al de la imagen

<img width="585" alt="envs 1" src="https://user-images.githubusercontent.com/11860880/30507829-63b2ff6a-9a60-11e7-8242-ce5df323fda4.png">
<img width="1222" alt="envs 2" src="https://user-images.githubusercontent.com/11860880/30507830-63e00f78-9a60-11e7-907c-9c09fc7fcd7c.png">

Y con eso ya tienen Heroku listo, ahora vamos a pasar a trabajar en el repo

Primero tienen que instalar la [línea de comando de Heroku](https://devcenter.heroku.com/articles/heroku-command-line)

Luego hacen login con su cuenta de Heroku en su terminal

```bash
heroku login
```

Luego coloquense en la carpeta de su repositorio y ejecuten los siguientes comandos donde
NOMBRE_HEROKU tienen que reemplazarlo con el **nombre de su aplicación en Heroku**

```bash
heroku git:remote -a NOMBRE_HEROKU # Guardar a donde suben su proyecto
heroku run sequelize db:migrate # Correr migraciones en la db de heroku
heroku run sequelize db:seed:all # Si tienen seeds corran esto
git push heroku master # Subir su proyecto a Heroku
```

Deberían tener un mensaje parecido a este

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  ^8.5.0
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  ^1.0.2
       
       Resolving node version ^8.5.0...
       Downloading and installing node 8.5.0...
       Using default npm version: 5.3.0
       Resolving yarn version ^1.0.2...
       Downloading and installing yarn (1.0.2)...
       Installed yarn 1.0.2
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.0.2
       [1/4] Resolving packages...
       success Already up-to-date.
       Done in 0.76s.
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 23.5M
-----> Launching...
       Released v7
       https://iic2513-2017-2-wican.herokuapp.com/ deployed to Heroku
Build finished
```

Con eso su aplicación debería estar funcionando en Heroku
Si no, pueden fijarse en la página de Heroku haciendo click en More y View logs
(También pueden hacerlo en su terminal con `heroku logs` o `heroku logs --tail` si quieren verlos en tiempo real)

<img width="244" alt="captura de pantalla 2017-09-15 a la s 22 01 20" src="https://user-images.githubusercontent.com/11860880/30507895-7a226eec-9a61-11e7-8702-4acaf0c947b4.png">

Y comentar esta issue con los errores que aparezcan para poder ayudarles :)

**Comment by Pyralspite** [comment]
Hola, cuando escribo ` heroku run sequelize db:migrate` me aparece

> Cannot find "/app/config/config.json". Have you run "sequelize init"?

Hice `heroku run sequelize init`, pero me sigue apareciendo el mismo mensaje. Que puedo hacer?

**Comment by roy350** [comment]
disculpa a mi me sale "bash: sequelize: command not found" cuando ejecuto heroku run sequelize db:migrate :C

**Comment by wachunei** [comment]
les funciona con `heroku run ./node_modules/.bin/sequelize db:migrate`?

**Comment by Pyralspite** [comment]
Me sigue apareciendo el mismo mensaje. 
En config hay un archivo config.json, lo borré, corrí sequelize init y el comando que pusiste, se creó de nuevo, pero sigue sin detectarlo :(

**Comment by wachunei** [comment]
No debes correr init, eso genera los archivos iniciales para empezar a configurar sequelize. En el template ya vienen esos archivos, con la configuración hecha.

**Comment by Airell98** [comment]
> No debes correr init, eso genera los archivos iniciales para empezar a configurar sequelize. En el template ya vienen esos archivos, con la configuración hecha.
> […](#)
> On Sep 16, 2017, 9:28 PM -0300, Pyralspite ***@***.***>, wrote: Me sigue apareciendo el mismo mensaje. En config hay un archivo config.json, lo borré, corrí sequelize init y el comando que pusiste, se creó de nuevo, pero sigue sin detectarlo :( — You are receiving this because you are on a team that was mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

angeur teu bisa mang, ngeus di tururan ku aing anu di medium teu bisa keneh,

**Comment by Airell98** [comment]
ngeus jiga nu gelo aing ngedploy ti ta tadi gagal wae euy
