### ISSUE TITLE
Librería moment.js

### ISSUE THREAD

**Issue by fnmendez** [IIC2513-2017-2/syllabus#12]
Hola,

Quisiera usar la librería [moment.js](https://momentjs.com) para tener mayor control sobre los _datetime_, sobre todo en cómo se muestran.

Gracias !

**Comment by wachunei** [comment]
La pueden utilizar 🙂

**Comment by raulmt** [comment]
Esta otra también es una buena alternativa, por si acaso: https://date-fns.org
