### ISSUE TITLE
Cuenta gratis en un storage para manejo de archivos

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#14]
Hola, escribo porque el profesor dijo en algún momento que había un proveedor donde nosotros como alumnos teníamos una cuenta gratis. ¿Cuál era? 
muchas gracias

**Comment by raulmt** [comment]
Microsoft Azure. Yo en clases usé Google Cloud que igual tiene como 1 año gratis o algo de es estilo. Amazon (AWS) también ofrece 1 año gratis.

Pero como consejo, creo que es mejor que dejen esos usos momentáneos gratis de AWS y Google para eventuales cosas futuras que hagan que no tengan relación con la universidad, y que mientras sean estudiantes aprovechen estos convenios como el con Microsoft Azure.

La otra opción que pueden usar para guardar archivos en "la nube" es Dropbox (no es tan bueno como los servicios anteriores que están pensados para este uso en todo caso… la orientación de Dropbox es diferente) aunque ahí no les sirve la librería que usamos en clases, `pkgcloud`… tendrían que usar el package de dropbox mismo, y tristemente ese package no maneja streams :(

**Comment by AlfonsoIgnacioV** [comment]
gracias!

**Comment by thomprycejones** [comment]
Me cuelgo para preguntar si puedo usar [Firebase](https://firebase.google.com/products/storage/?hl=es-419)

**Comment by raulmt** [comment]
@thomprycejones no hay restricciones en cuanto a dónde guardar los archivos que requiera su aplicación
