### ISSUE TITLE
Usar juice2 para mandar emails con CSS

### ISSUE THREAD

**Issue by flobarrios** [IIC2513-2017-2/syllabus#16]
Hola!

Buscando como agregar estilo a un email, noté que la única forma de hacerlo es declarando el CSS dentro del documento HTML ya que prácticamente no existen estándares para este. Como se que esto es una mala práctica, se me ocurren 2 soluciones:

1. Usar [juice2](https://www.npmjs.com/package/juice2), [premailer-api](https://www.npmjs.com/package/premailer-api) o algo similar que lo que hace este es insertar el CSS a partir de una hoja de estilo antes de enviar el email. 

2. Declarar el CSS dentro de un <style> tag en el html.

Si no, que recomiendan? 

Gracias!!

**Comment by raulmt** [comment]
Hola, qué bueno que te cuestionaste eso :)

Yo no quise que nos metiéramos demasiado en el tema de e-mails, al menos no de forma obligatoria, pues es un mundo tremendamente ingrato. Quienes hacen render del HTML+CSS que envíes son en general engines recortados o antiguos que no soportan varias de los elementos nuevos de estas dos tecnologías e incluso tienen mal/erróneo/incompleto soporte de algunos elementos antiguos. Incluso si revisas tu e-mail Gmail en un browser moderno, lo que muestra el contenido HTML+CSS no tendrá el mismo resultado que ver ese mismo documento directamente en el browser… y si agregas a los clientes nativos de correo, como Outlook y los del teléfonos móviles, esto sólo empeora aún más. En la práctica, crear un correo con estilos elaborados requiere de harta prueba y error, y son imprescindibles servicios como Litmus que te permiten ver imágenes de cómo se ve tu correo en múltiples clientes de correo.

Entre esas limitantes está el que pocos clientes soportan estilos CSS externos. Así que estás obligada, como bien llegaste a esa conclusión, a usar estilos inline en lo que se envíe finalmente al browser.

Es cierto que no es agradable escribir CSS inline, pero tampoco es agradable tener que probar en múltiples clientes de correo. Si quieres usar algo como juice está bien… la verdad no tengo algún CSS inliner para correos que recomendarte desde mi experiencia, pues no los he usado aún en Node.js. Lo que he hecho es más bien basarme en algún template de correo que haya sido cuidadosamente implementado de manera de ser compatible con múltiples lectores de correo y múltiples tamaños de dispositivo. Un ejemplo de estos, y open source además, es http://tedgoas.github.io/Cerberus/#css-inliners (te envié el link en donde específicamente no recomiendan usar CSS inliners con este template por ciertas razones).

**Comment by raulmt** [comment]
(Ah, y sólo para ser explícitos: si no vimos mucho en cuanto a HTML/CSS en e-mails y el template del curso tampoco incluye alguna solución muy buena al respecto, es porque tampoco en la corrección habrá mucho foco en cuanto a estilo en los correos… si tienen algo simple, quizá con un poco de estilos inline, pero que cumpla con su objetivo, está bien)
