### ISSUE TITLE
Sala de ayuda E4

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#17]
Estimados ayudantes: ¿sería posible establecer una sala de ayuda para esta entrega? 
Muchas gracias

**Comment by negebauer** [comment]
@IIC2513-2017-2/docentes

**Comment by wachunei** [comment]
Hola, al parecer ningún ayudante puede esta vez ☹️

**Comment by raulmt** [comment]
Pero trataremos de estar lo más atentos posibles al foro, cierto @IIC2513-2017-2/docentes ?

**Comment by AlfonsoIgnacioV** [comment]
Hola!
En realidad, para lo que necesito ayuda era para la parte de archivos. Estuve leyendo documentación, pero he perdido bastante tiempo en eso sin lograrlo. ¿Se podría subir alguna documentación sencilla para hacer esa parte? Muchas gracias!

**Comment by raulmt** [comment]
@AlfonsoIgnacioV En cuanto a manejo de archivos no hay un único proveedor de cloud storage a usar, y por lo mismo tampoco hay un único package que necesitas. En clases, en wican, usamos un package llamado `pkgcloud`, que es compatible con algunos proveedores, dentro de los cuales está Google Cloud Storage, que fue lo usado en wican. Ese package soporta algunos otros pocos servicios, pero no muchos. Si quisieras usar dropbox, por ejemplo, tendrías que usar el package de dropbox para ello. Por ahí me dijo un compañero tuyo que quería usar cloudinary, lo cual implica un package y procedimiento diferente.

Puedes ver el [commit de wican](https://github.com/IIC2513-2017-2/wican/commit/aaccfc8735bf27808d6a6444e0627bfbe698038f) al respecto para ver un uso de pkgcloud para download y upload, basado en la [documentación de ese package respecto a storage](https://github.com/pkgcloud/pkgcloud#storage).

La principal dificultad que han tenido algunos alumnos ha sido con la autenticación. En el caso de Google, el JSON que puedes descargar según lo indicado en la documentación de pkgcloud contiene los datos que wican está usando en ese setup.

Si estás teniendo un problema en particular puedes hacer la consulta más específica y podemos tratar de ayudarte; pero por lo que te mencioné anteriormente es difícil tener una guía para este tema.

**Comment by AlfonsoIgnacioV** [comment]
Hola!
Resolví ese problema... Pero ahora tengo otro diferente, y es que no está subiendo los archivos... 
Sería posible verlo de manera presencial? Que es una duda más específica y no sé si se pueda resolver por este medio.
Muchas gracias!

**Comment by wachunei** [comment]
Hola Alfonso, pudiste solucionar tu problema?
