### ISSUE TITLE
Problema push Heroku

### ISSUE THREAD

**Issue by mfuenzalida1** [IIC2513-2017-2/syllabus#18]
Hola
Con mi compañero hemos estado mucho tiempo intentando actualizar el contenido de nuestra aplicación en heroku pero no hemos tenido éxito. Intentamos hacerlo con yarn y npm pero tira el mismo error. Adjunto el error que sale en consola:

![22523725_10213010592193470_1938915139_n](https://user-images.githubusercontent.com/14151216/31617675-3a4b3340-b266-11e7-9cbc-638f69b2807c.png)

Agradeceríamos mucho su ayuda
Saludos

**Comment by raulmt** [comment]
por lo que se ve ahí parecen tener un error de sintaxis que les está impidiendo hacer build de los assets. Prueba corriendo localmente `yarn run build-assets`, que es el comando que te está fallando en heroku. Si no se ejecuta sin errores localmente, te seguirá fallando heroku, así que intenta pillar el error de sintaxis con eso localmente.

Ojo que ese comando lo que hace es ejecutar webpack, así que también podría ser que haya un problema en tu configuración de webpack, quizá intentando usar archivos orientados a servidor (ese app.js que se menciona me tinca que puede ser el app.js de server?)

**Comment by raulmt** [comment]
@mfuenzalida1 ese close significa que lo solucionaste? si es así, te agradecería compartir la solución por si alguien más tiene un problema similar
