### ISSUE TITLE
private_key en google storage

### ISSUE THREAD

**Issue by asimonv** [IIC2513-2017-2/syllabus#19]
Estoy tratando de agregar la private key como env variable, pero al parecer no se está autenticando. Cómo tengo que agregarla?
`"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANB......"` no mas?

**Comment by negebauer** [comment]
Si lo estas corriendo local puedes poner eso en un archivo y hacer
`KEY=$(cat archivo) yarn star`

En heroku lo puedes agregar en la parte de env vars

**Comment by asimonv** [comment]
Mmm tuve que hacer esto y definir GOOGLE_PRIVATE_KEY sin las comillas. 
```
module.exports = {
  private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
  client_email: process.env.GOOGLE_CLIENT_EMAIL,
};
```
que es básicamente remover los saltos de línea. Así pude definir las credentials como env vars.
