### ISSUE TITLE
Problema mandando email

### ISSUE THREAD

**Issue by mfuenzalida1** [IIC2513-2017-2/syllabus#20]
Hola!
Agregué la funcionalidad de mandar emails basándome en lo hecho en wican. Me cree una cuenta de sendgrid y agregué mis datos(usuario, contraseña de sendgrid y el api) en un .env para pasarlos como variables en config/email.js. Ademas cambié el "from" de la configuración a mi email usado en sendgrid. Al ejecutar el pedazo de código que manda el email no me tira ningun error pero no manda el email al usuario creado. Revisé los parámetros que recibe la funcion sendMail al ejecutarse y se pasan de forma correcta(tanto el email como el objeto user). No se que podría ser el problema. Help x(

**Comment by raulmt** [comment]
No se me ocurre a priori qué cosa te puede estar saliendo mal, pero un par de sugerencias para que investigues algo más a ver si el problema sale a la luz:
- nodemailer tiene una [opción de debug](https://nodemailer.com/smtp/#debug-options) que puedes activar, en que te mostrará los mensajes SMTP que se envían… quizá eso te puede dar alguna pista (tendrías que meterte a la parte del código en donde se crea el transport de nodemailer)
- puedes bajar wican mismo y ver si con tus credenciales te funciona el envío de correos (así descartas que sea algo con tu setup/código de envío de correo el problema)
- en la UI de sendgrid hay una sección en donde puedes ver los mensajes que se han enviado a tu cuenta de sendgrid. Si te aparece ahí (creo que se demora algunos minutos en aparecer en todo caso) entonces sabes que hasta ese punto quizá está bien, y quizá hay un tema con tu cuenta misma de sendgrid, o con el correo al cual intentas enviarle un mensaje, etc.

**Comment by raulmt** [comment]
@mfuenzalida1 lograste encontrar el problema?

**Comment by mfuenzalida1** [comment]
Si, muchas gracias por los consejos. Por alguna razón no me funcionaba con los correos de uc. Lo intenté con gmail y funcionó a la primera.
