### ISSUE TITLE
Un día más de plazo

### ISSUE THREAD

**Issue by flobarrios** [IIC2513-2017-2/syllabus#21]
Hola!!

Existe la posibilidad de dar un día más de plazo para esta entrega?  Se que no hay excusas pero estaría infinitamente agradecida con un poco más de tiempo para hacer una buena entrega!

Gracias  :blush:

**Comment by SHGoldfarb** [comment]
+1

**Comment by negebauer** [comment]
@SHGoldfarb para apoyar el pedido están las reacciones de GitHub (como el 👍 ), para seguir la issue uno se puede subscribir a la derecha. Evitemos los comentarios +1

**Comment by raulmt** [comment]
ok, domingo a la misma hora

**Comment by negebauer** [comment]
@IIC2513-2017-2/alumnos revisen ^
