### ISSUE TITLE
Consultas SQL en Sequelize

### ISSUE THREAD

**Issue by fagomez2** [IIC2513-2017-2/syllabus#23]
Hola! Tengo una consulta SQL que quiero utilizar para obtener todos los modelos de una clase en particular (proyectos) que han sido marcados como favoritos. La probé en PSQL y funciona, pero no se cómo implementarla en Sequelize.

La consulta es la siguiente: 

`SELECT "p"."id", "p"."name", "p"."updatedAt" FROM "projects" AS "p", "favorites" AS "f" WHERE ("p"."id" = "f"."projectId" and "f"."accountId" = '${ctx.session.accountId}')`

El problema que tengo es que no se cómo hacer que `ctx.orm.projects.findAll(` algo.. )` reconozca, además de la tabla Projects, a otra tabla (en este caso Favoritos). Busqué en la documentación y hablan de un atributo `include` pero no se cómo ocuparlo.

Cualquier ayuda es bienvenida ¡Gracias!

**Comment by wachunei** [comment]
Hola,

Según tu consulta, suponiendo que tienes los modelos `projects` y `favorites`, y además asumiendo que tienes definida la asociación entre ellas (ya sea a través de un modelo intermedio o no), quedaría como:

```js
const { accountId } = ctx.session;
const projects = await ctx.orm.projects.findAll({
  include: [{
    model: 'favorites',
    where: { accountId },
  }],
});
```

Si esto lo vas a utilizar recurrentemente lo puedes agregar como método al modelo (en el archivo del modelo):
```js
projects.findByAccountFavorites = function findByAccountFavorites(accountId) {
  return projects.findAll({
    include: [{
      model: 'favorites',
      where: { accountId },
    }],
  });
}
```

Con eso puedes hacer `ctx.orm.findByAccountFavorites(ctx.session.accountId)`.

**Comment by wachunei** [comment]
@fagomez2 funcionó al final?
