### ISSUE TITLE
En pedir no hay engaño

### ISSUE THREAD

**Issue by ivanwolf** [IIC2513-2017-2/syllabus#24]
Hola,
Existe la posibilidad de que tengamos más tiempo para esta entrega? React nos tomó mas tiempo de lo presupuestado 😢 
Muchas gracias de antemano!

**Comment by fadelafuente1** [comment]
👍 , ademas varios tenemos la I3 de Inteligencia artificial el martes :(

**Comment by lukassr** [comment]
![image](https://user-images.githubusercontent.com/10482758/32454993-a7e13e64-c2ff-11e7-9980-51bdb10f52e0.png)

**Comment by raulmt** [comment]
@IIC2513-2017-2/alumnos Respondí a través de un aviso en el SidIng
