### ISSUE TITLE
Obtener información de usuario actual para fetch

### ISSUE THREAD

**Issue by agmardones** [IIC2513-2017-2/syllabus#25]
Tenemos una componente que necesita información de un recurso de la aplicación; para esto, hacemos `fetch` al path del recurso, que corresponde a una ruta privada en nuestro contexto. Debido a esto, necesitamos incluir la información del usuario actual en el header para que el request sea efectivo, pero no sabemos de dónde obtener esta información para que el componente la pueda utilizar. ¿De qué forma/desde dónde podríamos obtener los datos del contexto actual?

**Comment by raulmt** [comment]
En [este commit](https://github.com/IIC2513-2017-2/wican/commit/af8411ea2323b20b5fe626e2d97c97c606c7d305) de wican que vimos en clases hay una manera de entregar datos desde el server (en el render inicial de la página) y que la app React puede luego usar como data inicial de la misma. ¿Te refieres a algo así?

La otra opción es tener un endpoint que te entregue toda la data del "current user", de manera que al llamarlo con las cookies correctas siempre podrás saber en el server qué usuario es y entregar la data correspondiente. Como los `fetch` que hagas desde React son requests normales hechos por el browser, incluirán siempre las mismas cookies que cualquier otro request del browser, sea o no XMLHttpRequest.

**Comment by wachunei** [comment]
Para que los requests creados con `fetch` incluyan las cookies debes activarlo con la opción `credentials`:
```js
fetch('/path/a/algun/recurso', {
  method: 'GET',
  headers: {
     'Content-Type': 'application/json',
  },
  credentials: 'include',
});
```

**Comment by agmardones** [comment]
Gracias por las respuestas, tenía lo último en el código, pero incluído dentro de headers. Al sacarlo y pasarlo como un parámetro aparte funcionó :clinking_glasses: .
