### ISSUE TITLE
Sala de ayuda E5

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#26]
Hola! Quería preguntar si hay alguna posibilidad de que se haga una sala de ayuda para esta tarea, o en su defecto, si podría haber algún ayudante disponible para atender consultas durante este viernes. 
Muchas gracias de antemano
Saludos :)

**Comment by wachunei** [comment]
Hola, voy a estar en el DCC ahora, desde las 10:20 aproximadamente, por dos horas. Estaré con alta probabilidad en la N. Friendly, si no, me buscan.
