### ISSUE TITLE
Activación de linter

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#27]
Hola! Uno de los ayudantes me recomendó que usara un archivo eslint, que era para activar un linter. No entendí mucho de qué se trata, ni de qué manera activar el linter. El ayudante me mostró un código y me dijo que un par de archivos que hacían esto, habían  sido subidos. 
¿Dónde encuentro esos archivos y cómo puedo activarlos?

Muchas gracias
Saludos!

**Comment by wachunei** [comment]
Hola!

En las dependencias del proyecto ya está incluido [ESLint](https://eslint.org) como linter. En su sitio dice:
> Code linting is a type of static analysis that is frequently used to find problematic patterns or code that doesn’t adhere to certain style guidelines.

<hr>

Los archivos que te mencioné son archivos de [configuración](https://eslint.org/docs/user-guide/configuring) del linter que estamos usando. En sus proyectos (también [en wican](https://github.com/IIC2513-2017-2/wican/blob/master/.eslintrc)) ya está la configuración para los archivos del servidor, la que les puede faltar es [la de los archivos de React](https://github.com/IIC2513-2017-2/wican/blob/master/src/assets/js/.eslintrc).

En los scripts declarados en `package.json` hay dos que pueden llegar y usar para *lintear* su código: `yarn lint` y `yarn lint-fix`, con ellos pueden ver si están rompiendo alguna de las reglas que decidimos usar ([usamos las de airbnb](https://github.com/airbnb/javascript)). La idea es que minimicen ese número de errores y advertencias. 😃

Lo que te recomiendo es usar algún package en tu editor de texto que ejecute el linter a medida que vas editando, la idea es que reconozca los archivos de configuración del proyecto y además use la versión instalada en tus dependencias (en `./node_modules/`).

No sé cuáles son los paquetes recomendados para Sublime, pero en Atom uso [linter](https://atom.io/packages/linter) + [linter-eslint](https://atom.io/packages/linter-eslint).

**Comment by AlfonsoIgnacioV** [comment]
Listo! Muchas gracias!

**Comment by AlfonsoIgnacioV** [comment]
Hola de nuevo! Sorry, pero tuve otro problema. Me está tirando todos los errores de otros archivos, **menos los de jsx**. De tal manera, errores como los que me indicabas ayer, no los está detectando (el error donde faltaba la "s", por ejemplo). 

Me tira un error sobre best practices, pero no especifica nada. Me puse a mirar el archivo, pero no me arrojaba luces de qué podría estar ocurriendo. 

Además, se me murió el CSS y me tira un error más o menos, ¿te pasó algo parecido?
Saludos!

**Comment by wachunei** [comment]
Hola, ese error es porque tenemos malas las dependencias, para arreglarlo ayer hice lo siguiente, hay dos opciones:

## A mano

* Ejecutar `npm info "eslint-config-airbnb@latest" peerDependencies`
* Instalar cada una de las dependencias listada con yarn `yarn add --dev <dependency>@<version>`

## No tan a mano 

Ejecutar 
```sh 
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs yarn add --dev "$PKG@latest"
)
```

que hace exactamente lo mismo.

Estas instrucciones están en el [README del package `eslint-config-airbnb`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

**Comment by AlfonsoIgnacioV** [comment]
Hola! Hice eso, lo hice a mano (uno por uno) porque me tiraba unos errores, pero aún así me sigue tirando lo mismo. Cuando hago `npm info "eslint-config-airbnb@latest" peerDependencies` aún me aparece que faltan los mismos pares. También cuando hago `yarn install` aparece como que esas dependencias están fallando. 

¿Qué más se puede hacer? Probé la otra versión, pero no me corría por alguna razón.
Muchas gracias
Saludos

**Comment by wachunei** [comment]
`npm info "eslint-config-airbnb@latest" peerDependencies`solamente te las va a listar, eso no signifique que falten.

Trata de poner acá los errores para tener alguna idea para ayudarte.

**Comment by AlfonsoIgnacioV** [comment]
Gracias! (Visto presencialmente)
