### ISSUE TITLE
Duda de enunciado E6

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#28]
Hola! Tengo una duda respecto a lo que dice el enunciado. Cito: 

_Esta última evaluación, en conjunto con la demo final, es lo que generará la nota final de su proyecto, 50% de la nota de proyecto del curso. La otra mitad será el promedio de todas las entregas parciales (6 entregas) realizadas durante el semestre._

Mi duda es respecto de si la nota de la E6 influye o no en la nota final, ya que aunque se requiere un 50% de avance al menos para la entrega 6, no se especifica esto (según como lo entendí yo)

Gracias!
Saludos

**Comment by wachunei** [comment]
Tienes razón que está medio confuso, pero es así:
```js
notaProyecto = avg(avg(E1, E2, E3, E4, E5, E6), EFinal)
```
en donde `avg()` retorna el promedio de sus argumentos.

**Comment by raulmt** [comment]
Sí, u otra forma de decirlo: el proyecto (50% de la nota final del curso) está compuesto en un 50% de la nota final y un 50% del promedio de todas las entregas parciales.

Ahora, esa "nota final" del proyecto está a su vez compuesta de 3 partes:
- nota por la presentación/demo
- nota evaluación general de la aplicación (funcionalidad final lograda)
- nota evaluación técnica de la aplicación (cómo la funcionalidad anterior fue construida)

Ese párrafo que citas, junto a lo que está justo antes de ese párrafo, hablan también de este último punto, la evaluación técnica. La nota de presentación/demo y la aplicación las evaluamos el mismo día de la demo. Pero la evaluación técnica necesita mayor tiempo de dedicación para examinarla la aplicación en detalle, y es por eso que la evaluación técnica se basa en lo que tengan en el repositorio en la fecha de la entrega 6. Pueden mejorar su aplicación posterior a esa fecha, e influirá en una mejor nota general de aplicación, pero no en la evaluación técnica.

**Comment by AlfonsoIgnacioV** [comment]
Ah y otra pregunta relacionada con lo mismo.. La evaluación en la demo será discreta como lo ha sido para las entregas? Muchas gracias!

**Comment by raulmt** [comment]
Sí, nunca usamos notas que no sean discretas pues los sistemas de la U no soportan números reales, por ejemplo :)

Pero sí, será una nota de 1 a 7 como con las que se sienten más cómodos ;)
