### ISSUE TITLE
Temario I3

### ISSUE THREAD

**Issue by KatherineGuerrero** [IIC2513-2017-2/syllabus#29]
Hola! Quería consultar si la materia de APIs entra en esta prueba o quedaría para el examen?
Gracias desde ya!

**Comment by andresfdezc** [comment]
Sumándome a esto, podrían subir las clases que faltan?

**Comment by thomprycejones** [comment]
Me sumo para preguntar cuál sería **todo** el temario. Gracias!

**Comment by raulmt** [comment]
API no entra para la I3, sino para el examen. Entra hasta lo último que han aplicado en entregas (E5, React).

Nos vemos!

**Comment by raulmt** [comment]
Ah, y respecto al material de clases, por si acaso todo lo que entra en la I3 ya está subido desde hace algún tiempo. Lo de API falta, pero como les dije, no entra en esta prueba.
