### ISSUE TITLE
Duda codigos javascript

### ISSUE THREAD

**Issue by roy350** [IIC2513-2017-2/syllabus#30]
Hola, en los codigos dejados para estudiar en la carpeta Javascript II, me queda la duda de la linea de codigo  ```Perro.prototype = Object.create(Mamifero.prototype);``` del archivo clases_prototipo.js, no entiendo muy bien que hace esa linea de codigo, de hecho la comente y no afecto en nada el programa, entonces queria saber cual es su importancia, de antemano muchas gracias! :D

**Comment by wachunei** [comment]
Lo que hace esa línea (en adelante *la* línea) es asignar al prototipo de `Perro` un objeto que tiene prototipo `Mamifero`.

En el ejemplo comentar la línea no tiene ningún efecto en el funcionamiento, ya que al objeto perro se le ejecutan métodos que se le asignan a su prototipo (ya sea su prototipo `Perro`, en caso de que comentes la línea mencionada, o en caso contrario `Mamifero`)

Si el prototipo de `Mamifero` tuviera método que no está sobrescrito por `Perro`, en caso de comentar la línea e intentar ejecutarlo, tu programa fallaría.

Ejemplo: En el próximo código `respira` es un método del prototipo de `Mamifero`. Si comentas la línea, al ejecutar `perro.respira()` en la cadena de prototipos nunca encontraría ese método y tu programa falla. Si dejas la línea tal cual, el prototipo de `perro` es `Mamifero` y podrá respirar.

```js
function Mamifero(name) {
  this.getName = function() {
    return name;
  };

  this.setName = function(theName) {
    name = theName;
  };
}

Mamifero.prototype.habla = function() {
  console.log('...' + this.getName());
};

Mamifero.prototype.respira = function() {
  console.log(`${this.getName()} ha respirado`);
}

function Perro(name) {
  Mamifero.call(this, name);
}

Perro.prototype = Object.create(Mamifero.prototype);

Perro.prototype.habla = function() {
  console.log(this.getName() + ': guau!');
};

const perro = new Perro('Snoopy');
perro.getName();
perro.habla();
perro.respira();
perro.setName('Pluto');
perro.habla();
perro.respira();

const nuevoMamifero = new Mamifero('una jirafa');
nuevoMamifero.habla();
nuevoMamifero.respira();
```

**Comment by roy350** [comment]
Muchas gracias por tu respuesta!, me quedo claro :), ahora viendo el codigo se me genero otra pregunta :O, cual es la principal diferencia entre usar o no $, se que hace referencia al uso de jquery, pero la verdad no comprendo muy bien su debido uso! muchas gracias nuevamente!

**Comment by raulmt** [comment]
Esta pregunta tiene que ver con lo conversado en clases hoy, ¿cierto? Usar algo como jQuery no te provee nada que no puedas hacer directamente con la API expuesta por el browser a través del DOM. Sin embargo, estas librerías suelen entregarte dos ventajas importantes:
- una API más agradable/simple/expresiva de usar (aunque con recientes actualizaciones del DOM ya tiene menor peso esto)
- incluyen una capa de compatibilidad de manera que tu código funcione exactamente igual en diferentes browsers, aún cuando algunos de éstos tengan APIs diferentes o tengan errores en su implementación
