### ISSUE TITLE
¿Cómo se puede ver si las rutas para una API están funcionando?

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#33]
Hola! Mi pregunta apunta al hecho de que, en el caso de usar una ruta de la UI, resulta directo ver que si se renderea una vista determinada, corresponde a un determinado recurso, por ejemplo una iniciativa. Sin embargo, no sé muy bien de qué manera hacer algo análogo o parecido con una ruta de la API (para efectos de prueba más que nada), ya que me tira un _Not Found_ , el cual atribuyo al hecho de que no se tiene una vista en este caso. 

Espero que se entienda!
Muchas gracias
Saludos

**Comment by wachunei** [comment]
Hola,

Si estás respondiendo JSON a un `GET`, definitivamente tu browser debería renderear el contenido en texto plano, como por ejemplo el resultado de las votaciones de hoy: http://servelelecciones.cl/data/elecciones_presidente/computo/global/19001.json

Puedes usar herramientas para generar las consultas con diferentes métodos HTTP, headers, body, etc. Para la línea de comando puedes usar [httpie](https://httpie.org/) y con una interfaz puedes usar [Postman](https://www.getpostman.com/).

Espero que esto sea la respuesta a tu duda

**Comment by AlfonsoIgnacioV** [comment]
Me falló la instalación de httpie y estoy probando a ver cómo me va con Postman...
Sí, en parte me responde la duda, pero, ¿se supone que esto debería ocurrir con la Wican? Estoy probando con ella, y pongo literalmente la URL de la API, es decir, estoy poniendo directamente _localhost:3000/api/auth_ , no obstante me aparece _Not Found_ . No entiendo de qué manera podría hacerse esta autentificación sin usar una vista de por medio

**Comment by wachunei** [comment]
Lo que pasa es que [esa ruta es un `POST`](https://github.com/IIC2513-2017-2/wican/blob/master/src/routes/api/auth.js#L6), puedes hacerla con Postman pasando los parámetros en el body.

**Comment by AlfonsoIgnacioV** [comment]
Sí! Ahí logré (cambiando algunas cosas al principio) que me mostrara el JSON, tal como me habías dicho. Gracias!
