### ISSUE TITLE
Código de la parte de consumir una API

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#34]
Hola! Escribo para pedir, si fuera posible, que por favor suban la parte de código en que se está consumiendo una API.

Muchas gracias!
Saludos

**Comment by flobarrios** [comment]
Me sumo a la petición! 🙏

**Comment by raulmt** [comment]
Listo, subido (aunque crear un cliente de API es tan sólo usar alguna librería como superasen o axios de una manera mínimamente organizada :) ). También subí las slides por si acaso.

**Comment by AlfonsoIgnacioV** [comment]
Gracias!
