### ISSUE TITLE
Duda arquitectura

### ISSUE THREAD

**Issue by mandrade2** [IIC2513-2017-2/syllabus#35]
Hola! Cuando agregamos invitaciones y notificaciones para los usuarios se nos extendió mucho el archivo de rutas para usuarios ya que esta todo la lógica de las invitaciones y notificaciones ahí. Pasó de tener ~150 lineas a ~500 lineas por lo que no es cómodo trabajar ahí ya sea para modificar algo de usuarios, notificaciones o invitaciones. 
¿Es esto un problema de arquitectura o esta bien y no tiene mayor importancia? o quizás notificaciones e invitaciones deberían estar definidas en un archivo separado?

**Comment by raulmt** [comment]
En general es aconsejable no tener archivos muy extensos. Y siempre hay alguna manera relativamente sencilla de separarlos en cuanto a diferentes "concerns", aún cuando quieras que compartan un mismo path base.

Por ejemplo, si en users.js tienes definido un router que está montado en `/users`, y quieres que las notifications estén en un path como `/users/:userId/notifications` puedes crear un router en que tengas un GET a `/` en un archivo `notifications.js` que luego importas en `users.js` para montar sobre ese router en el path correspondiente: `usersRouter.use('/notifications', notificationsRouter.routes())`. De esa manera tienes todo el código de routes handlers de notifications en un archivo aparte, y tu archivo de users sólo necesitó agregar una única línea (bueno, 2 si cuentas el `require` :) ).

**Comment by mandrade2** [comment]
Muchas gracias! Queda mucho mejor así

**Comment by mandrade2** [comment]
Muchas gracias! Queda mucho mejor así
