### ISSUE TITLE
Plazo E6

### ISSUE THREAD

**Issue by fnmendez** [IIC2513-2017-2/syllabus#36]
Hola,

¿Es posible que por favor se dé un poco más de  plazo (p. ej. hasta el jueves)?

Si no, ¿subir la documentación más tarde?

Muchas gracias

@raulmt @wachunei @negebauer

**Comment by wachunei** [comment]
@IIC2513-2017-2/alumnos El plazo se extiende hasta las 23:59:59 de hoy
