### ISSUE TITLE
Enunciado I3

### ISSUE THREAD

**Issue by andresfdezc** [IIC2513-2017-2/syllabus#37]
¿Podrían subir el enunciado de la I3 para estudiar? Aprovechando su atención, ¿están todas las presentaciones subidas? Da la impresión de que faltan algunas de las últimas.

**Comment by raulmt** [comment]
@andresfdezc listo el enunciado https://github.com/IIC2513-2017-2/syllabus/tree/master/evaluaciones/I3

Respecto a las slides, sí están todas salvo por las de usabilidad, que más que contenido era para guiar una conversación/discusión en torno a eso. No entra en el examen de mañana tampoco. ¿Es esa la que echabas de menos u otra?

**Comment by andresfdezc** [comment]
No tengo claro cuáles no estaban porque falté unos días, pero se veía extraño que pasara de la carpeta 13 a la 15

**Comment by andresfdezc** [comment]
Gracias por el enunciado!

**Comment by raulmt** [comment]
si, la 14 que falta ahí es la carpeta de usabilidad que te mencionaba
