### ISSUE TITLE
Sobre la demo final del proyecto

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#38]
Hola! Escribo para preguntar a qué horas será la demo el día jueves 30 y cuál será la duración aproximada que ésta va a tener.

Muchas gracias
Saludos!

**Comment by raulmt** [comment]
El FAQ que publiqué hace un par de días responde ambas preguntas. Si tienes dudas adicionales nos cuentas :)
