### ISSUE TITLE
Duda multipart

### ISSUE THREAD

**Issue by asimonv** [IIC2513-2017-2/syllabus#40]
Hola, he estado tratando de mandar request por fetch con react, pero no puedo leer los archivos desde koa, cómo tiene que ser el request? He probado quitándole los headers y agregándole `'Content-Type': 'multipart/form-data'` más su boundary  (porque así se supone que el browser le agrega el boundary y el content-type), pero tampoco me funciona. El ctx.request.files resulta {}.

Cómo debería ser? Gracias! :(

Edit: Así se ve el payload:

<img width="386" alt="screen shot 2017-11-29 at 8 44 00 am" src="https://user-images.githubusercontent.com/7036160/33373614-80496aa4-d4e1-11e7-8b1d-87cd2ca7692f.png">

**Comment by raulmt** [comment]
Cuando quieres usar multipart (que para archivos mezclados con datos lo necesitas) lo mejor es usar FormData, que es un objeto que puedes armar a partir de un form o bien ir completándolo con los datos que tú quieras (append).

Aquí hay un ejemplo en que lo usan a partir de un form, y le añaden más cosas: https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#Sending_files_using_a_FormData_object

Ese ejemplo usa XMLHttpRequest, pero fetch igual soporta FormData.

Si no puedes procesar el file a subir a través del form, puedes también obtener la instancia File seleccionada en un input type file a través del DOM (https://developer.mozilla.org/en-US/docs/Web/API/FileList).

Te recomiendo usar esto de manera de que no tengas que hacerlo tan a bajo nivel armando el request. Si recuerdo bien, FormData automáticamente hará que el request sea multipart y con un boundary por el hecho de haber agregado un File a la data a enviar.

**Comment by asimonv** [comment]
Gracias profe! @wachunei me ayudó y me explicó por qué era el error.

**Comment by raulmt** [comment]
y nos vas a dejar a todos metidos sin contarnos nada???? 😭

**Comment by asimonv** [comment]
JAJAJAJA. El problema era que le estaba pasando un state al FormData y no el form en sí! Espero que esto resuelva el misterio 👀.
