### ISSUE TITLE
Error al iniciar la aplicación

### ISSUE THREAD

**Issue by alexvonbergeno** [IIC2513-2017-2/syllabus#5]
Hola!
Tengo un error al iniciar la aplicación con yarn start o con node index.js.
Error:
`Unable to connect to the database: { SequelizeConnectionError: password authentication failed for user "username"`
con username el nombre de usuario de mi computador. Estoy usando linux mint.

Mi duda es si tengo que crear un usuario en postgresql y como hacerlo para que sequelize se pueda conectar automaticamente.

**Comment by wachunei** [comment]
Hola!
El mensaje de error dice que estás tratando de autenticarte en la base de datos con el usuario "username", lo más probable es que no exista esa cuenta en tu postgres.

Revisa la documentación de [createdb](https://www.postgresql.org/docs/9.6/static/app-createdb.html) y crea una base de datos con algún usuario y contraseña, luego los seteas como variables de entorno, para que el archivo `src/config/database.js` las interprete (son las variables `DB_USERNAME`, `DB_NAME` y `DB_PASSWORD`)

**Comment by alexvonbergeno** [comment]
Ahi me funciono, tuve que transformarme a superusr y editar el src/config/database.js para que lo aceptara. Gracias por la ayuda!

**Comment by wachunei** [comment]
Bien! Asegúrate de no exponer las credenciales en tu código 👌🏽
https://github.com/IIC2513-2017-2/syllabus/wiki/Comenzando-el-desarrollo#base-de-datos

**Comment by tiborchers** [comment]
Hola,

El template tiene alguna forma automática de setear las variables de entorno? La única forma que encontramos es corriendo `export DB_USERNAME=<user>`en la consola antes de correr la aplicación.

**Comment by negebauer** [comment]
@tiborchers  Pueden también hacerlo sin usar export de esta manera
`DB_USERNAME=<user> yarn start`
De esa manera la variable de entorno solo esta definida en el scope de la aplicación

**Comment by wachunei** [comment]
@tiborchers en [Tips](https://github.com/IIC2513-2017-2/syllabus/wiki/Tips#variables-de-entorno) hay ahora una sección sobre variables de entorno y cómo setearlas
