### ISSUE TITLE
Ayuda con el router

### ISSUE THREAD

**Issue by ivanwolf** [IIC2513-2017-2/syllabus#6]
Hola, tengo el siguiente problema,
En un controlador tengo definido los métodos `get` `/:id` para mostrar un objeto y `get` `/new` para mostrar el formulario que crea uno. El problema es que cuando trato de acceder al 'new' la app ejecuta el método en la ruta /:id y define id = 'new'. Luedo sequalize se cae. A alguien le pasa algo similar? Quizás este haciendo algo mal. Cualquier ayuda es bienvenida.

**Comment by SHGoldfarb** [comment]
Prueba definiendo primero el `get /new` y mas abajo el `get/:id`

**Comment by negebauer** [comment]
El orden en la definición de las rutas es importante

Recuerda que la manera en que funciona es que va entrando en cada ruta que hace match y si no hay un llamado a next() termina ahí

Con poner /new antes de /:id deberías estar bien 👌🏻

**Comment by ivanwolf** [comment]
Funciona perfecto, muchas gracias
