### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by asimonv** [IIC2513-2017-2/syllabus#7]
Se que no es necesario por ahora, pero qué nos recomiendan usar para crear una session o hacer login?

**Comment by raulmt** [comment]
Hay un package ya agregado en el template que es koa-session. Eso te permite almacenar información en una cookie, y que podrás leer en todos los requests sucesivos. El manejo de sesión lo haremos basándonos en ese package.

En la clase del jueves veremos qué son y cómo funcionan las cookies, y cómo koa-session utiliza eso para permitirnos crear esta "ilusión de estado" en un protocolo que es stateless (HTTP). Y también lo implementaremos en wican ;)

**Comment by asimonv** [comment]
Gracias profe!
