### ISSUE TITLE
Static content

### ISSUE THREAD

**Issue by asimonv** [IIC2513-2017-2/syllabus#8]
Hola, quiero usar css, pero no encontré algo en el template. Cómo podemos usar static content + routes? Estuve viendo koa-static, pero no sé si podemos usarlo tampoco. Gracias!

**Comment by asimonv** [comment]
Ya encontré cómo! ✨
1. Instalé [koa-static](https://github.com/koajs/static) -> `npm install koa-static --save`.
1. Cree la carpeta `src/static` y dentro de ella la carpeta `css`.
2. En `app.js` agregué `app.use(serve(path.join(__dirname, 'static')))`.

**Comment by raulmt** [comment]
El PR a sus repos con lo necesario para usar CSS viene en camino, para la E3.

Mientras tanto está bien si usas koa-static. De todas formas usaremos ese package para la configuración de producción. Pero en development usaremos webpack con una configuración que nos permite hot-reload como vimos en la clase de hoy.

De todas maneras podrás directamente usar tus archivos CSS cuando hagas merge del PR con webpack. Probablemente sólo necesitarás cambiarlo de directorio (y deshacer algo de la config que agregaste).
