### ISSUE TITLE
Usuario y contraseña en archivo src/config/database

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2513-2017-2/syllabus#9]
Hola! Mi duda es la siguiente: para hacer correr la aplicación wican incluyendo la base de datos, tenía el problema de que me decía que el usuario "por defecto" no correspondía con la contraseña también "por defecto". ¿Hay alguna manera de solucionar esto que no sea poniendo directamente mi usuario y contraseña en src/config/database? 
Muchas gracias!

**Comment by negebauer** [comment]
Revisa #5

**Comment by AlfonsoIgnacioV** [comment]
Gracias!
